-- Drop Contact_customFields_gin_idx — a GIN index built with the
-- `jsonb_path_ops` operator class, which serves ONLY the @>, @?, @@ containment
-- operators. A repo-wide grep finds ZERO uses of any of those on
-- Contact.customFields. The three actual customFields query shapes all bypass
-- it:
--   1. quick-search   c."customFields"::text ILIKE '%..%'   (text cast, not @>)
--   2. field filter    c."customFields" ->> key ILIKE '%..%' (extraction, not @>)
--   3. (no @>/@? key-containment query exists anywhere)
--
-- So the index is pure write overhead: every Contact UPDATE (and ingest bumps
-- lastInboundAt on every inbound message) pays GIN maintenance for an index no
-- plan can use. It was also the project's long-standing "single-permanent-diff"
-- pain — hand-managed out of schema.prisma because Prisma's jsonb_path_ops
-- emitter re-flags it as drift every `migrate dev`. Dropping it removes both
-- the write tax AND that drift workaround.
--
-- If exact-key/value containment search (customFields @> '{"plan":"pro"}') is
-- ever genuinely needed, recreate it as a DEFAULT jsonb_ops GIN (which also
-- serves the `?` key-exists operator) — not jsonb_path_ops.
--
-- IF EXISTS = idempotent. No CONCURRENTLY (migrate transaction; brief lock).

DROP INDEX IF EXISTS "Contact_customFields_gin_idx";
