-- Email verification becomes real.
--
-- `emailVerified` defaulted to TRUE, so any string matching an email regex
-- created a fully working account. That is a demo signup, not a product one:
-- there was no proof anyone could receive mail at the address, which also meant
-- password reset and every future notification had nowhere to go.
--
-- New rows now default FALSE and are gated until a 6-digit OTP is confirmed.
--
-- EXISTING rows are left TRUE deliberately. Every current account arrived
-- through the invite flow or the seed, so the address was already vouched for;
-- flipping them to false would lock out every live user at deploy time to prove
-- something we already know.
ALTER TABLE "User" ALTER COLUMN "emailVerified" SET DEFAULT false;
