-- AlterEnum
ALTER TYPE "BroadcastStatus" ADD VALUE 'scheduled';

-- NOTE: Prisma autogenerated a `DROP INDEX "Contact_customFields_gin_idx"` here
-- and it was STRIPPED on purpose (recurring trap — see project memory). That GIN
-- index is defined via raw SQL in 0_init, not in schema.prisma, so every
-- migrate-dev wants to drop it. Dropping it kills custom-field filtering. Left
-- out so a prod `migrate deploy` never removes it.

-- AlterTable
ALTER TABLE "Broadcast" ADD COLUMN     "name" TEXT,
ADD COLUMN     "scheduledAt" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX "Broadcast_teamId_scheduledAt_idx" ON "Broadcast"("teamId", "scheduledAt");
